apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-dynamic-pv
  namespace: infra
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8G
  storageClassName: aws-ebs
